# Generated by Django 4.0.5 on 2022-07-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
        migrations.AddField(
            model_name='service',
            name='is_payable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='vender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin_App.vender'),
            preserve_default=False,
        ),
    ]
