# Generated by Django 4.0.5 on 2022-07-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_alter_order_is_added_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Running'), (2, 'Pending'), (3, 'Complete'), (4, 'Cancelled')], default=2, max_length=1),
        ),
    ]
